### ISSUE TITLE
Latest set of commits broke old build systems

### ISSUE THREAD

**Issue by rcarson3** [llnl/ExaCMech#7]
It appears that commits f99e6b2a01e16bff6b3093adb4d016619d9e6819 and 2f217651914ba8198461bf5f13d2ef64b734e7c7 broke existing build systems. The new additions added there should only be run if a version of RAJA was built with external dependencies. If we didn't explicitly define CUB or camp we should default to the old paths for how things were done.

**Comment by nrbarton** [comment]
Hmm... I tested it against RAJA built without external dependencies. But it turns out it was an old RAJA build ... maybe 0.7 ... so it maybe did not trigger the issues that you saw. I will add camp_DIR and CUB_DIR to the conditionals. @rcarson3 can you let me know if that does not do the trick. I should start building against a more recent RAJA for my testing, but I am not sure when I will get to that.

**Comment by rcarson3** [comment]
Thanks and RAJA v0.11.0 should be a good one to update to.  It's what is currently used for ExaConstit. Also, I'll test it and let you know, and if need be work on fixes.

**Comment by rcarson3** [comment]
Tested the new commit on RAJA 0.11 and 0.12.1 and both appear to work now. So, I'll go ahead and close this.
